custom:
  - "https://www.udemy.com/course/linux-command-line-volume1/?couponCode=KEEPLEARNING"
  - "https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp/"
  - "https://www.udemy.com/course/data-structures-algorithms-python/"
  - "https://www.udemy.com/course/complete-linux-training-course-to-get-your-dream-it-job/"
  - "https://www.udemy.com/course/wordpress-for-beginners-course/"
  - "https://www.udemy.com/course/aws-certified-cloud-practitioner-new/"
  - "https://www.udemy.com/course/build-your-blockchain-az/"
  - "https://www.udemy.com/course/the-complete-javascript-course/"
