name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * 0'  # runs every Sunday at midnight UTC
  workflow_dispatch:      # lets you trigger it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with WakaTime stats
        uses: athul/waka-readme@v1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
